var os=require('os')

console.log(os.type()) 
console.log(os.arch())   
console.log(os.hostname()) 
console.log(os.platform())
console.log(os.release())
console.log(os.version())
console.log(os.userInfo()) 
console.log(os.totalmem())
console.log(os.freemem())